language: generic
os: osx

env:
  global:
    # Branch (or any remote ref, i.e. pull/10/head) to fetch
    - BUILD_BRANCH=master
    # Commit tag/ref to checkout
    - BUILD_COMMIT=3.17.0

cache:
  ccache: true
  directories:
    - ~/Library/Caches/pip
    # cache used by build-macos-app.sh
    - ~/.cache/pkgs

before_install:
  - git clone -q --depth 20 https://github.com/biolab/orange3.git
  - cd orange3
  - git fetch origin $BUILD_BRANCH
  - git checkout $BUILD_COMMIT

install:
  - if [[ -d /Applications/Orange3.app ]]; then rm -rf /Applications/Orange3.app; fi
  # TODO: If this is a tagged commit, then it would be preferable to use
  #       the (to be) published whl files (i.e. from the staging index so the
  #       wheels, installers, .. can go live at the same time)
  - ./scripts/macos/build-macos-app.sh --pip-arg={-r,../specs/macos/requirements.txt,./} /Applications/Orange3.app
  - ./scripts/macos/create-dmg-installer.sh --app /Applications/Orange3.app dist/Orange3.dmg
  #  reversed("LMAY KCUF")
  - "VERSION=$(/Applications/Orange3.app/Contents/MacOS/pip show orange3 | grep -E '^Version: ' | cut -d ' ' -f 2)"
  - mv dist/Orange3.dmg dist/Orange3-$VERSION.dmg
  - cd ..

script:
  # run the tests in the application's environment, but move it to a different
  # location first
  - mkdir -p ~/Applications
  - mv -f /Applications/Orange3.app ~/Applications/
  - ~/Applications/Orange3.app/Contents/MacOS/python --version
  - ~/Applications/Orange3.app/Contents/MacOS/pip --version
  - ~/Applications/Orange3.app/Contents/MacOS/pip freeze

  # Don't even ask
  - export ORANGE_DEPRECATIONS_ERROR=1
  - export PYTHONWARNINGS=module
  - ~/Applications/Orange3.app/Contents/MacOS/python -m unittest -v Orange.tests Orange.widgets.tests

after_success:
  - shasum -a 256 orange3/dist/Orange3-*.dmg
  - curl -fS --upload-file orange3/dist/Orange3-*.dmg https://transfer.sh/
