environment:
  global:
    # git repo from which to pull orange3 sources
    REPO: https://github.com/biolab/orange3.git
    # Branch/ref from which to pull
    BUILD_BRANCH: master
    # Commit ref/tag to checkout
    BUILD_COMMIT: 3.4.5

    # fixes build env dependencies for building orange3 wheels
    BUILD_DEPS: --only-binary numpy --extra-index-url=https://pypi.anaconda.org/ales-erjavec/simple numpy==1.9.3 wheel

  # Note the python version here refers to the one included in the installer
  # not the one used for building/packaging
  matrix:
    - PYTHON_VERSION: 3.4.4
      PLATTAG: win32
      ENVSPEC: scripts/windows/specs/PY34-win32.txt
      PYTHON: C:\Python34

    - PYTHON_VERSION: '3.6'
      CONDA: C:\Miniconda36-x64\Scripts\conda
      PYTHON: C:\Miniconda36-x64\python

matrix:
  fast_finish: true

cache:
  - '%LOCALAPPDATA%\pip\Cache -> appveyor.yml'

build_script:
  - git clone -q --depth 20 %REPO%
  - cd orange3
  - git fetch origin %BUILD_BRANCH%
  - git checkout %BUILD_COMMIT%

  - set "PATH_BEFORE_BUILD=%PATH%"
  - set "PATH=C:\msys64\usr\bin;C:\Program Files (x86)\NSIS;%PATH%"

  - if not "%CONDA%" == "" ( ..\ci\appveyor-conda-build.bat )
  - if "%CONDA%" == "" ( ..\ci\appveyor-build.bat )

  - for %%s in ( dist/Orange3*.exe ) do ( set "INSTALLER=%%s" )
  - echo INSTALLER = %INSTALLER%

  - set "PATH=%PATH_BEFORE_BUILD%"
  - cd ..

test_script:
  # cleanup registry of anaconda reg keys
  - reg delete HKEY_LOCAL_MACHINE\Software\Python\ContinuumAnalytics /f
  - reg delete HKEY_CURRENT_USER\Software\Python\ContinuumAnalytics /f
  - dir orange3\dist
  # Install in silent mode. Output has to be piped somewhere so the installer
  # runs 'attached' to the console.
  - orange3\dist\%INSTALLER% /S /D=C:\test-install > nul
  # The venv and conda envs create different install layouts.
  - if "%CONDA%" == "" ( set "PYTHON=C:\test-install\Scripts\python" )
  - if not "%CONDA%" == "" ( set "PYTHON=C:\test-install\python" )
  - >-
    "%PYTHON%" --version
  - >-
    "%PYTHON%" -m pip --version
  - >-
    "%PYTHON%" -m pip freeze
  # Test that orange and all dependencies are installed in a consistent state
  - >-
    "%PYTHON%" -m pip install --no-index --no-cache-dir orange3

  # Run test suite in the installed environment.
  - set ORANGE_DEPRECATIONS_ERROR=1
  - set PYTHONWARNINGS=module
  - >-
    "%PYTHON%" -m unittest Orange.tests Orange.widgets.tests
  - mkdir installers
  - move orange3\dist\%INSTALLER% installers\

  # Log the filename and the sha checksum
  - for /f %%s in ( 'sha256sum -b installers/%INSTALLER%' ) do ( set "CHECKSUM=%%s" )
  - echo INSTALLER = %INSTALLER%
  - echo SHA256    = %CHECKSUM%


artifacts:
  - path: installers\*
  - path: conda-pkgs\*

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: Nxnsu1AhdU0JXv7T18xJ9mWnLNe6/M1NND+tV6IYU8pdPs97hGbNaprSv2T24/N2
  artifact: installers\*.exe
  draft: True
  on:
    appveyor_repo_tag: true        # deploy on tag push only
