environment:
  global:
    REPO: https://github.com/ales-erjavec/orange3.git
    # Branch/ref from which to pull
    BUILD_BRANCH: win-app-reboot
    # Commit ref/tag to checkout
    BUILD_COMMIT: FETCH_HEAD

    # fixes build env dependencies for building orange3 wheels
    BUILD_DEPS: --only-binary numpy --extra-index-url=https://pypi.anaconda.org/ales-erjavec/simple numpy==1.9.3 wheel

  # Note the python version here refers to the one included in the installer
  # not the one used for building/packaging
  matrix:
    - PYTHON_VERSION: 3.4.4
      PLATTAG: win32
      ENVSPEC: scripts/windows/specs/PY34-win32.txt

      PYTHON: C:\Python34

matrix:
  fast_finish: true

cache:
  - '%LOCALAPPDATA%\pip\Cache -> appveyor.yml'

build_script:
  - git clone -q --depth 20 %REPO%
  - cd orange3
  - git fetch origin %BUILD_BRANCH%
  - git checkout %BUILD_COMMIT%

  - ..\ci\appveyor-build.bat

  - cd ..

test_script:
  # Install in silent mode. Output has to be piped somewhere so the installer
  # runs 'attached' to the console.
  - dir orange3\dist
  - orange3\dist\%INSTALLER% /S /D=C:\test-install > null

  - C:\test-install\Scripts\python --version
  - C:\test-install\Scripts\pip --version
  - C:\test-install\Scripts\pip freeze
  - C:\test-install\Scripts\pip install --no-index --no-cache-dir orange3

  # Run test suite in the installed environment.
  - set ORANGE_DEPRECATIONS_ERROR=1
  - set PYTHONWARNINGS=module
  - C:\test-install\Scripts\python -m unittest Orange.tests Orange.widgets.tests
  - mkdir installers
  - move orange3\dist\%INSTALLER% installers\

  - set PATH=C:\msys64\usr\bin;%PATH%
  - bash -c "sha256sum -b installers/*.exe"


artifacts:
  - path: installers\*

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: Nxnsu1AhdU0JXv7T18xJ9mWnLNe6/M1NND+tV6IYU8pdPs97hGbNaprSv2T24/N2
  artifact: installers\*.exe
  draft: True
  on:
    appveyor_repo_tag: true        # deploy on tag push only
