environment:
  global:
    # Orange version
    VERSION: 3.4.1
    # Repo from which to pull
    REPO: https://github.com/ales-erjavec/orange3.git
    # Branch to pull (can also be any ref on remote i.e.
    # release-staging/$VERSION or even pull/1/head)
    BRANCH: win-app-reboot
    # commit id on branch (a tag or a sha identifier)
    COMMIT: 3.4.1

  matrix:
    - SPECARGS: --platform win32 --python-version 3.4.4
      PYTAG: 34
      PLATTAG: win32

    - SPECARGS: --platform win_amd64 --python-version 3.5.3
      PYTAG: 35
      PLATTAG: win_amd64

cache:
  - '%LOCALAPPDATA%\pip\Cache'

build_script:
  - git clone --depth 30 -q --branch "%BRANCH%" %REPO%
  - cd orange3
  - git checkout -qf "%COMMIT%"
  - set PATH=C:\msys64\usr\bin;%PATH%
  - set PATH=C:\Python35;C:\Python35\Scripts;%PATH%
  - set PATH=C:\Program Files (x86)\NSIS;%PATH%
  - bash orange3/scripts/windows/build-win-installer.sh %SPECARGS%

test_script:
  - set INSTALLER=Orange3-%VERSION%-Python%PYTAG%-%PLATTAG%.exe
  # install in silent mode
  - dist/%INSTALLER% /S /D=C:\test-install > null
  # run test suite
  - set ORANGE_DEPRECATIONS_ERROR=1
  - set PYTHONWARNINGS=module
  - C:\test-install-dir\python -m unittest Orange.tests Orange.widgets.tests

  - mkdir installers
  - move dist/%INSTALLER% installers\

artifacts:
  - path: installers\*
