ignore: {% set data = load_setup_py_data() %}
ignore: {% set version = data['version'] %}

package:
  name: orange3
  version: {{ data['version'] }}

source:
  git_url: ../../orange3

build:
  number: 0
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main

  osx_is_app: True

  script:
    - python setup.py config --with-htmlhelp build -j1 bdist_wheel
    - if errorlevel 1 exit 1        # [win]
    - pip install --no-deps --no-cache --no-index -f dist Orange3=={{ version }}
    - if errorlevel 1 exit 1        # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - pip
    - wheel
    - sphinx
  run:
    - python
    - setuptools    >=36.3
    - numpy         >=1.13.0
    - scipy
    - scikit-learn  >=0.20.0
    - bottleneck    >=1.2.1
    - chardet       >=2.3.0
    - docutils
    - xlrd          >=0.9.2
    - xlsxwriter
    - keyring
    - keyrings.alt  # for alternative keyring implementations
    - pyqt
    - pyqtgraph     >=0.10.0
    - anyqt         >=0.0.8
    - joblib        >=0.9.4
    - python.app    # [osx]
    - serverfiles
    - python-louvain >=0.13
    - matplotlib    >=2.0.0
    - opentsne      >=0.3.0
    - pandas

test:
  # Python imports
  imports:
    - Orange
    - Orange.canvas
    - Orange.canvas.application
    - Orange.canvas.canvas
    - Orange.canvas.canvas.items
    - Orange.canvas.document
    - Orange.canvas.gui
    - Orange.canvas.help
    - Orange.canvas.preview
    - Orange.canvas.registry
    - Orange.canvas.scheme
    - Orange.canvas.styles
    - Orange.canvas.utils

    - Orange.widgets
    - Orange.widgets.data
    - Orange.widgets.evaluate
    - Orange.widgets.model
    - Orange.widgets.unsupervised
    - Orange.widgets.visualize

    - Orange.classification
    - Orange.clustering
    - Orange.data
    - Orange.distance
    - Orange.evaluation
    - Orange.modelling
    - Orange.preprocess
    - Orange.projection
    - Orange.regression
    - Orange.statistics

  commands:
#    - python -m unittest -v Orange.tests
    - orange-canvas --help
    - python -c "import pkg_resources as pr; pr.require('Orange3')"

about:
  home: http://orange.biolab.si/
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Orange, a component-based data mining framework.'
